### ISSUE TITLE
Support JSON as return format

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/PartnerWizard#4]
Some APIs like the [Fitzwilliam Museum](http://data.fitzmuseum.cam.ac.uk/api/?) only deliver JSON. The Wizard should support JSON as return format.

**Comment by schloett** [comment]
Add-on question to this issue: The web-interface for the Partner-Wizard provides a button to select between XML and JSON as response format, is this just a dummy button, or this issue already fixed?
Not far below the button it is stated that "The API configured in the sections below, need to return the data in XML-format". So I guess there is not yet full support for JSON? Or can I just plug the corresponding attributes in?

**Comment by jr-dig-orgel** [comment]
The PartnerWizard already supports JSON. If you choose JSON, then the PartnerWizard transforms the returned JSON to XML, and shows the transformed XML in the webapp.
